[package]
name = "classified_shamir"
version = "0.1.1"
edition = "2024"

license = "MIT OR Apache-2.0"
description = "shamir secret sharing using the honest and classified crates"

authors = ["James Hunt <jameshuntdevelopment@gmail.com>"]
repository = "https://github.com/jameshuntt/classified_shamir"


[dependencies]
rand_utils = "0.1.0"
honest = "0.1.4"
classified = "0.1.1"

rand = "0.9.0"
secrecy = "0.10.3"
num-traits = "0.2.19"
num-integer = "0.1.46"
num-bigint = { version = "0.4.6", features = ["rand"] }
subtle = { version = "2.6.1", features = ["std"] }

zeroize = { version = "1.8.1", features = ["derive"] }
